spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbcrtmysql://127.0.0.1:3306/fresh?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: a
    
   http:
    encoding:
       force: true
       charset: UTF-8
       enabled: true
    
      
      
   session:
      store-type: redis
      
   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      jedis:
         pool:
            max-active: 8
            
   mail:
      host: smtp.qq.cpm
      username: 2675657329@qq.com
      password: hvnktgkexeghebhj
      port: 465
      portocol: smtp
      properties:
         mail:
            smtp:
               auth: true
               sll: 
                  enable: true
                  
#mybatis配置
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.yc.dayfreshspringboot.goods.entity #要扫描的启用别名的类所在的包
  
  
eureka:
   client:
      service-url:
         defaultZone: http://navy:13456@127.0.0.1:6868/eureka
               